baseURL = 'http://gohugo.io/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "posts"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
author = "dree"
user = "dree"
hostname = "dree.blog"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/dreeSec"

[[params.social]]
key = 2
name = "CTFtime"
url = "https://ctftime.org/user/122661"

[[params.social]]
key = 3
name = "email"
url = "mailto:dree.31415@gmail.com"
